cache:
- c:\sr -> stack.yaml
- C:\Users\appveyor\AppData\Local\Programs\stack\x86_64-windows -> stack.yaml

clone_folder: "c:\\stack"
environment:
  global:
    STACK_ROOT: "c:\\sr"
  matrix:
    - stack_lts: "lts-7.19"
    - stack_lts: "nightly"

matrix:
  allow_failures:
    - stack_lts: "nightly"

install:
- curl -sS -ostack.zip -L --insecure http://www.stackage.org/stack/windows-x86_64
- 7z x stack.zip stack.exe
- stack --no-terminal setup --resolver %stack_lts% > nul

build_script:
- stack --no-terminal build --resolver %stack_lts% --reconfigure

test_script:
- stack --no-terminal test --resolver %stack_lts% --reconfigure

deploy: off
